site_name: What is Trending on YouTube?
repo_url: https://github.com/NeonOrangeOrange/YT-Trending
edit_uri: ""
site_url: https://NeonOrangeOrange.github.io/YT-Trending/

nav:
  - Home: index.md
  - Trending:
    - US (United States): trending/US.md

markdown_extensions:
  - toc:
      toc_depth: 1
