# This is a basic workflow to help you get started with Actions

name: test_CI

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install depenencies
        run: python -m pip install -r requirements.txt

      - name: Update the lists
        env:
            API_KEY: ${{ secrets.API_KEY }}
        run: python update_trending_lists.py

      - name: Update the website
        run: python -m mkdocs gh-deploy
